language: node_js

node_js:
    - '12'

matrix:
    include:
        - os: linux
            dist: xenial
            sudo: required
        - os: osx
        - os: windows

cache:
    npm: true

install:
    - npm install

script:
    - npm run dist

# deploy:
#   provider: releases
#   api_key: $ENCRYPTED_GITHUB_TOKEN
#   skip_cleanup: true
#   on:
#     tags: true
