language: node_js

node_js:
- '12'

cache: npm

jobs:
  include:
  - stage: lint
    script: npm run lint
    os: linux
    dist: xenial

    # - stage: test
    #   script: npm test

  - stage: build
    script: npm run dist
    os: linux
    dist: xenial
    sudo: required
  - os: osx
    script: npm run dist
  - os: windows
    script: npm run dist

  - stage: deploy
    if: branch = v0.7.0
    os: linux
    dist: xenial
    deploy:
      provider: releases
      file_glob: true
      file:
      - dist/bookjournal*.tar.gz
      - dist/bookjournal*.deb
      api_key:
        secure: "$GITHUB_TOKEN"
      skip_cleanup: true
      on:
        tags: true
        repo: eiskalteschatten/BookJournal
  - os: osx
    if: branch = v0.7.0
    deploy:
      provider: releases
      file_glob: true
      file: dist/BookJournal*.dmg
      api_key:
        secure: "$GITHUB_TOKEN"
      skip_cleanup: true
      on:
        tags: true
        repo: eiskalteschatten/BookJournal
  - os: windows
    if: branch = v0.7.0
    deploy:
      provider: releases
      file_glob: true
      file: dist/BookJournal*.exe
      api_key:
        secure: "$GITHUB_TOKEN"
      skip_cleanup: true
      on:
        tags: true
        repo: eiskalteschatten/BookJournal

stages:
- lint
- build
- deploy
