language: node_js

node_js:
- '12'

env:
- API_KEY: h2Mme9oLKLKVoiuAAsNpeODWaou2d5nzPhWb8YhrHt6vf45O5jEQqatVbEO4MlXGi0OTnpVvxqkziP853KgFbVLCHO1N4FN4n6LGd+u4u/36zEXkjJ6DEsKPbfeRbKkUbwKNlFHOeIn3xcxsMInm0XfOQuwf5D/R2LnyMqchRW6PA6+iTy0KexNyB651rVhevdAbadgcJXj32eQ6JucaRuzTvQTGy1EeZqHGOAzcRzNNQCtrZKCOXrb2AFfgAodg5Qx9BTbTi3HWAXnt3qfUqm2wKRkHxYzcqL9CTNpoz9YoRNKfkyVGMPgIjbyNueJ+z3bKRkJq2/iCLNOQLy5UAKT2GO85NPlu73DyZwo/oVsw7BaAsaTfK+XoTmVWtHyBRmU5bLXmKOG4dKCOZJnf62mXGnzg5H9isBlgrS82uoLnzkPYgToThTfjtjL48G/HBU6X1ghfWkrcdK39n+9LB4Gc50tH0JO/3Sua+jeWwJpXuqeV4XotOuy6ZsB/TiPu9jYAEPb76lsg5UYBqXVJQ5H2bWfmwWzKAIkWbddsoBALWNchT0HdngC/i8GrTGkHsR/BG2HilwaKvnF8EtjW+lhQPPE07q2UGoBanMElqMqV2T4HpL3BJZCsjsi2v5pHR3v5T9prfRvoQ5x7d8DWVu6YRWR5GvDH3E0jvMvzJPE=

cache: npm

jobs:
  include:
  - stage: lint
    script: npm run lint
    os: linux
    dist: xenial

    # - stage: test
    #   script: npm test

  - stage: build
    script: npm run dist
    os: linux
    dist: xenial
    sudo: required
  - os: osx
    script: npm run dist
  - os: windows
    script: npm run dist

  - stage: deploy
    if: branch = v0.6.0
    os: linux
    dist: xenial
    deploy:
      provider: releases
      file_glob: true
      file:
      - dist/bookjournal*.tar.gz
      - dist/bookjournal*.deb
      api_key:
        secure: "$API_KEY"
      skip_cleanup: true
      on:
        tags: true
        repo: eiskalteschatten/BookJournal
  - os: osx
    if: branch = v0.6.0
    deploy:
      provider: releases
      file_glob: true
      file: dist/BookJournal*.dmg
      api_key:
        secure: "$API_KEY"
      skip_cleanup: true
      on:
        tags: true
        repo: eiskalteschatten/BookJournal
  - os: windows
    if: branch = v0.6.0
    deploy:
      provider: releases
      file_glob: true
      file: dist/BookJournal*.exe
      api_key:
        secure: "$API_KEY"
      skip_cleanup: true
      on:
        tags: true
        repo: eiskalteschatten/BookJournal

stages:
- lint
- build
- deploy
